[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
bridge = { path = "../bridge" }
mainline = "6.0"
axum = "0.7"
sha1 = "0.10"
hex = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8"
tower-http = { version = "0.5", features = ["cors", "fs"] }
md5 = "0.7"
urlencoding = "2.1.3"
